language: objective-c
xcode_project: SwiftCrypt.xcodeproj
xcode_scheme: SwiftCrypt
osx_image: xcode8.2
script:
    - xcodebuild clean build -sdk iphonesimulator -project SwiftCrypt.xcodeproj -scheme SwiftCryptTests
